### ISSUE TITLE
/usr/bin/ld: cannot find /usr/local/lib: File format not recognized collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by kkhuang1990** [seung-lab/znn-release#101]
when I tried to run the make command at the znn-release root dir, some error came out:

/usr/bin/ld: cannot find /usr/local/lib: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [test] Error 1

the whole output in terminal is like this:

Makefile:33: warning: overriding commands for target `malis'
Makefile:22: warning: ignoring old commands for target `malis'
g++ -o ./bin/test src/cpp/malis_test.cpp -g -I./src/include -I./zi -I. /usr/local/lib -DNDEBUG -O3 -std=c++1y -DZNN_CUBE_POOL_LOCKFREE -DZNN_USE_FLOATS  -lfftw3 -lfftw3f -lpthread -pthread -lrt
In file included from src/cpp/malis_test.cpp:6:0:
./src/include/cube/cube_io.hpp: In function ‘znn::v4::cube_p<T> znn::v4::read(const string&, const vec3i&) [with F = double; T = float; znn::v4::cube_p<T> = std::shared_ptr<znn::v4::cube<float> >; std::string = std::basic_string<char>; znn::v4::vec3i = zi::vl::vec<long int, 3ul>]’:
./src/include/cube/cube_io.hpp:37:17: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
                 static_cast<void>(fread(&v, sizeof(F), 1, fvol));
                 ^
./src/include/cube/cube_io.hpp: In function ‘znn::v4::cube_p<T> znn::v4::read(const string&, const vec3i&) [with F = double; T = int; znn::v4::cube_p<T> = std::shared_ptr<znn::v4::cube<int> >; std::string = std::basic_string<char>; znn::v4::vec3i = zi::vl::vec<long int, 3ul>]’:
./src/include/cube/cube_io.hpp:37:17: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
/usr/bin/ld: cannot find /usr/local/lib: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [test] Error 1

Looking forwards to your reply!

**Comment by xiuliren** [comment]
Hi @kkhuang1990 , thanks for your interest of this package. unfortunately, this package was deprecated in favor of 
https://github.com/seung-lab/znnphi-release

I would suggest to try our docker image if you still would like to try this package. 
https://hub.docker.com/r/jpwu/znn/

**Comment by kkhuang1990** [comment]
thanks for your reply. I tried to download your project from docker
https://hub.docker.com/r/jpwu/znn/
however, error came out like this

Using default tag: latest
Error response from daemon: manifest for jpwu/znn:latest not found

Best regards!

---------------------------------------------------
黄 凱凱 (D2)    Kaikai HUANG (D2)
東京大学 大学院情報理工学系研究科
知能機械情報学専攻 原田牛久研究室 E2-81C1
The University of  Tokyo
Graduate School of Information Science and Technology
Dept. Mechano-Informatics   Harada-Ushiku Lab. E2-81C1
Phone: 080-9640-2628
E-mail: huang@mi.t.u-tokyo.ac.jp
---------------------------------------------------

2017-10-18 1:18 GMT+09:00 Jingpeng Wu <notifications@github.com>:

**Comment by xiuliren** [comment]
take a look at the available tags, you have to use znn:v0.1.4
https://hub.docker.com/r/jpwu/znn/tags/
