### ISSUE TITLE
MALIS: IndexError: list index out of range

### ISSUE THREAD

**Issue by petteriTeikari** [seung-lab/znn-release#41]
When trying the segmentation for 2-PM data with MALIS weighing on, I get the following error:

```python
znn-release/python/emirt/volume_util.py:160: RuntimeWarning: overflow encountered in double_scalars
  tsz[r1-1] = tsz[r1-1] + tsz[r2-1]

Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main( sys.argv[1] )
  File "train.py", line 112, in main
    re += rand_errors.values()[0]
IndexError: list index out of range
```

The output for `rand_errors` indeed seems empty from that call in `train.py`:
```python
malis_weights, rand_errors = cost_fn.malis_weight(pars, props, lbl_outs)
```

But how should that be defined then so that I get some rand errors? `malis_weights` and `grdts` contained values with the `output` key

**Comment by jingpengwu** [comment]
are you using the master branch?

could you please try the `malis` branch?

**Comment by petteriTeikari** [comment]
Oh, well I cloned the `malis` branch and compiled both `pymalis.cpp` and `pyznn.cpp`, but still get the following then trying to train with the default `config.cfg` file:

```python
znn-releaseMALIS/python$ python train.py config.cfg 
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    import test
  File "znn-releaseMALIS/python/test.py", line 9, in <module>
    from core import pyznn
ImportError: No module named core
```

**Comment by jingpengwu** [comment]
Oh, I did not add the `__init__.py` file. Please update the code and try again.

**Comment by petteriTeikari** [comment]
Thanks for that, so now I got pass that but had then:

```python
start training...
start from  99401
Segmentation fault (core dumped)
```

Which may then be for several reasons I guess

**Comment by petteriTeikari** [comment]
Do you have any preferred way to get .crash file or core if there is something to be done for that?

**Comment by jingpengwu** [comment]
There is a `is_log` flag to turn on the log recording system. This may provide some hints.

**Comment by jingpengwu** [comment]
@petteriTeikari Here is a warning. Note that the `malis` function is still experimental. Whether it is effective is not quite clear.

**Comment by hsseung** [comment]
@petteriTeikari we recommend that you use the `reorganize` or `master` branch.  Other branches are experimental with known bugs.  MALIS is not working yet.

**Comment by petteriTeikari** [comment]
Okay for the MALIS issues @jingpengwu and @hsseung, and I keep using the master branch then
