### ISSUE TITLE
sampling probability balance among training datasets

### ISSUE THREAD

**Issue by jingpengwu** [seung-lab/znn-release#62]
Currently, we use uniform probability among different datasets. This works fine with similar size training volume. In case the size of training datasets differs a lot, this sampling may not be appropriate. At least, we should have a choice to balance the probability of patch source according to the number of candidate locations.

To support the mask function, we should directly get probability according to number of candidate locations among different training datasets.

**Comment by nicholasturner1** [comment]
Another way to do this might be to let the user define specific weights with which to sample different datasets. That weight would be easy to input as the # of candidate locations. I should be implementing something like this over the weekend.

**Comment by jingpengwu** [comment]
this was fixed by:
https://github.com/seung-lab/znn-release/pull/75
