### ISSUE TITLE
Network-dependent error, no obvious flaws in network spec file

### ISSUE THREAD

**Issue by AlexanderRiordan** [seung-lab/znn-release#90]
I'm receiving the following error message when attempting to train a network:
<img width="558" alt="screen shot 2016-05-05 at 1 30 08 pm" src="https://cloud.githubusercontent.com/assets/19211225/15051230/86da0638-12c5-11e6-85f3-a8b3b19479b4.png">

Switching the specified network in the config file solves the problem. Thus there's something about the network file that is likely causing the error. I've also verified that the intended network file is being called by train.py. Network spec file below. Please advise. 

[N3.znn.zip](https://github.com/seung-lab/znn-release/files/250849/N3.znn.zip)

**Comment by nicholasturner1** [comment]
Found the issue - specified an 'ouput' instead of an 'output'
